apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: buckets.epca.eo
spec:
  conversion:
    strategy: None
  group: epca.eo
  names:
    kind: Bucket
    listKind: BucketList
    plural: buckets
    shortNames:
      - bucket
    singular: bucket
  preserveUnknownFields: true
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
